# Generated by Django 6.0.6 on 2026-06-18 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_phone_number_remove_user_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
