# Generated by Django 6.0.6 on 2026-06-26 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_approved_therapistprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TherapistProfile',
        ),
    ]
